### ISSUE TITLE
index.ts is not part of the compilation output

### ISSUE THREAD

**Issue by nim4n** [JavadRasouli/angular2-persian-pipes#4]
I get this error in angular5:
ERROR in ./node_modules/angular2-persian-pipes/index.ts
Module build failed: Error: /home/nim4n/src/order_web/node_modules/angular2-persian-pipes/index.ts is not part of the compilation output. Please check the other error messages for details.
    at AngularCompilerPlugin.getCompiledFile (/home/nim4n/src/order_web/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:649:23)
    at plugin.done.then (/home/nim4n/src/order_web/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 @ ./src/app/app.module.ts 63:31-64
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

 and i fix it by adding below line to the tsconfig.app.json:

  "include": [
    "../src/**/*",
    "../node_modules/angular2-persian-utils/index.ts",
    "../node_modules/angular2-persian-pipes/index.ts"
  ],

**Comment by HoseinGhanbari** [comment]
"node_modules/angular2-persian-utils/**/*.ts",
    "node_modules/angular2-persian-pipes/**/*.ts"
